### 1. Register a new user
# send this request first to create a new user account. You can change the email and password if you want.

POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123",
  "username": "testuser"
}

### 2. Login with the new user

# after successful login, copy "access_token" từ response and use for the next requests.
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

### 3. Test Get Videos 
#after successful login, copy the "access_token" from the response and replace YOUR_TOKEN_HERE below
GET http://localhost:3000/videos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJpYXQiOjE3NzE3NDYyNDgsImV4cCI6MTc3MTc0NzE0OH0.qFv_egFhM02A5a41I7CFrbOuG3lqBr_2SWYawTlIBPM

### 4. Direct Upload Video 
# Upload video and metadata in a request (multipart/form-data)
POST http://localhost:3000/videos/upload
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJpYXQiOjE3NzE3NDYyNDgsImV4cCI6MTc3MTc0NzE0OH0.qFv_egFhM02A5a41I7CFrbOuG3lqBr_2SWYawTlIBPM
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="title"

My TikTok Style Video
--MyBoundary
Content-Disposition: form-data; name="description"

This is a direct upload.
--MyBoundary
Content-Disposition: form-data; name="file"; filename="1111.mp4"
Content-Type: video/mp4

< ./1111.mp4
--MyBoundary--

### 5. Delete Video 
# Change :videoId with the ID video you want to delete (get the ID from the request  3 or 4)
DELETE http://localhost:3000/videos/18
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJpYXQiOjE3NzE3NDgwMzAsImV4cCI6MTc3MTc0ODkzMH0.OpXqvcwpsxdE5wuwZMFZOdu4b79g1SMC7lNoITN4Cs0

### 6. Apply for Creator
# Apply to be a Creator
POST http://localhost:3000/applications
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJpYXQiOjE3NzE3MjI5NzYsImV4cCI6MTc3MTcyMzg3Nn0.Veg8N3gAY18qXcYdUfn25PTdGepbGncZsQXce_m68qE
Content-Type: application/json

{
  "capabilityCode": "live.creator",
  "notes": "I want to stream games"
}

### 7. Subscribe 
# sign for Premium (simulator)
POST http://localhost:3000/subscriptions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJpYXQiOjE3NzE3MjQwNDcsImV4cCI6MTc3MTcyNDk0N30.NTF_6ByF79HMGW5L6HzvNY6uK7JovhwB4yirgxXXu-E
Content-Type: application/json

{
  "planCode": "premium"
}

### 8. Check Subscription 
# check the current subscription status
GET http://localhost:3000/subscriptions/current
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJpYXQiOjE3NzE3MjQwNDcsImV4cCI6MTc3MTcyNDk0N30.NTF_6ByF79HMGW5L6HzvNY6uK7JovhwB4yirgxXXu-E

### 9. Cancel Subscription 
#cancel the current subscription
POST http://localhost:3000/subscriptions/cancel
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJpYXQiOjE3NzE3MjQwNDcsImV4cCI6MTc3MTcyNDk0N30.NTF_6ByF79HMGW5L6HzvNY6uK7JovhwB4yirgxXXu-E